import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/cupertino.dart';
// import 'package:persistent_bottom_nav_bar/persistent-tab-view.dart';
// import "package:bubble_bottom_bar/bubble_bottom_bar.dart";
import 'package:bottom_navy_bar/bottom_navy_bar.dart';
import 'package:project_coba/KepalaSekolah/models/models.dart';
import 'package:project_coba/KepalaSekolah/viewModels/view_models.dart';
import 'package:project_coba/widgets/card_courses.dart';
import 'dart:ui';
import 'package:project_coba/widgets/theme.dart';
import 'package:flutter_swiper/flutter_swiper.dart';

part 'MainBoarding.dart';
part 'profile.dart';
part 'home.dart';
part 'pengumuman.dart';
part 'jadwal_pelajaran.dart';
part 'tugas.dart';
part 'mataPelajaran.dart';
part 'tugasPage.dart';
part 'data.dart';
part 'bottomBar.dart';
// part 'Template.dart';
